language: ruby
rvm:
  - 2.5.1

before_script:

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: 
 - set -e # halt script on error
 - bundle exec jekyll build
 - bundle exec htmlproofer --http-status-ignore "999" ./_site

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false

deploy:
  provider: pages
  local-dir: ./_site
  skip_cleanup: true
  name: Deployment Bot
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  repo: Andrew-Kulpa/Andrew-Kulpa.github.io
  keep_history: true
  target-branch: master
  on:
    branch: master
